---
title: "Datos agrupados"
author: "jerf"
date: "11/6/2021"
output: html_document
---
```{r}
ChickWeight

pesos <-ChickWeight$weight
pesos
n<-length(pesos)
```


### Regla de Sturges
$k = [1+log_2(n)]$

```{r}
k1<-ceiling(1+log(n,2))
k1

A1 <-diff(range(pesos)) / k1
round(A1)

L1<-min(pesos)-1/2*1
L1

L<- L1+ A1*(0:11)
L

X1 <- (L[1] + L[2]) / 2
X1

X<-X1 + A1 * (0:10)
X
```


### Regla de la raíz cuadrada
$k = [\sqrt{n}]$

```{r}
k2<-ceiling(sqrt(n))
k2

A2 <-diff(range(pesos)) / k2
round(A2)

L1<-min(pesos)-1/2*1
L1

L<- L1+ A2*(0:11)
L

X1 <- (L[1] + L[2]) / 2
X1

X<-X1 + A2 * (0:10)
X
```


### Regla de Scott

```{r}
As <-3.5 * sd(pesos) * n ^(-1/3)
k3<-ceiling(diff(range(pesos))/As)
k3

A3 <-diff(range(pesos)) / k3
round(A3)

L1<-min(pesos)-1/2*1
L1


L<- L1+ A3*(0:11)
L

X1 <- (L[1] + L[2]) / 2
X1

X<-X1 + A3 * (0:10)
X

```



### Regla de Freedman-Diaconis

```{r}
Afd<- 2*(quantile(pesos, 0.75, names = FALSE)- quantile(pesos, 0.25, names = FALSE)) * n^(-1/3)
k4 <- ceiling(diff(range(pesos))/Afd)
k4

A4 <-diff(range(pesos)) / k4
round(A4)

L1<-min(pesos)-1/2*1
L1


L<- L1+ A4*(0:11)
L

X1 <- (L[1] + L[2]) / 2
X1

X<-X1 + A4 * (0:10)
X

```

