---
title: "Visualizing Carbon Dioxide Levels"
author: "Emanuel Fitta"
date: "26/5/2021"
output: html_document
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries and data
library(readr)
library(dplyr)
library(ggplot2)
```
## NOAA data

### Inspecting data

```{r error=TRUE}
options(scipen=10000) #removes scientific notation

noaa_data <- read_csv("carbon_dioxide_levels.csv")
head(noaa_data)
```

### Visualazing data
```{r}
noaa_viz <- ggplot(data = noaa_data, aes(x = Age_yrBP, y = CO2_ppmv)) + 
  geom_line() + 
  labs(title = "Carbon Dioxide Levels From 8,000 to 136 Years BP", subtitle = "From World Data Center for Paleoclimatology and NOAA Paleoclimatology Program", x = "Years Before Today (0=1950)", y = "Carbon Dioxide Level (Parts Per Million)")+ scale_x_reverse(lim=c(800000,0))
noaa_viz
```


## IAC data

### Inspecting data
```{r}
iac_data <- read_csv("yearly_co2.csv")
head(iac_data)
```

### Visualazing data

```{r}
iac_viz <- ggplot(data = iac_data, aes(x = year, y = data_mean_global))+
  geom_line()+
  labs(title = "From Institute for Atmospheric and Climate Science (IAC).", x = "Year", y = "Carbon Dioxide Level (Parts Per Million)")

iac_viz
```

### Max CO2 ppmv

```{r}
millenia_max <- max(noaa_data$CO2_ppmv)
millenia_max

```

### Adding to IAC graph

```{r}
iac_viz + geom_hline(aes(yintercept = millenia_max, linetype = "Historical CO2 Peak before 1950"), color = "red")


```

