---
title: "Tabla de frecuencias de datos agrupados"
author: "jerf"
date: "15/6/2021"
output: pdf_document
---

# Funcion que calcula la tabla de frecuencias de datos agrupados
```{r}
TablaFrecs <- function(x, k, A, p){
  L = min(x)-p/2+A*(0:k)
  x_cut = cut(x, breaks = L, right = FALSE)
  intervals = levels(x_cut)
  mc = (L[1]+L[2])/2 +A*(0:(k-1))
  Fr.abs = as.vector(table(x_cut))
  Fr.rel = round(Fr.abs / length(x), 4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
}
```

```{r}
TablaFrecs.L <- function(x, L, V){
  x_cut = cut(x, breaks = L, right = FALSE, inclue.lowest = V)
  intervals = levels(x_cut)
  mc = (L[1:(length(L)-1)] + L[2:length(L)]) / 2
  Fr.abs = as.vector(table(x_cut))
  Fr.rel = round(Fr.abs / length(x), 4)
  Fr.cum.abs = cumsum(Fr.abs)
  Fr.cum.rel = cumsum(Fr.rel)
  tabla = data.frame(intervals, mc, Fr.abs, Fr.cum.abs, Fr.rel, Fr.cum.rel)
  tabla
}
```

```{r}
library(MASS)
cw <- crabs$CW
TablaFrecs(cw,10,1.3, 0.1)
```

```{r}
TablaFrecs.L(cw,10,FALSE)

```



